### ISSUE TITLE
error:Could not allocate txin   

### ISSUE THREAD

**Issue by 271083359** [NetboxGlobal/Netbox.Wallet#1]
I followed the operation of the document, but there was an error. May I ask how to solve this problem
![微信图片_20190927134344](https://user-images.githubusercontent.com/32384503/65744997-d7645c00-e12c-11e9-8553-b2bc1d737f5e.png)

**Comment by NetboxGlobal** [comment]
Does the problem still exists? Asuming that you have wrong txid in masternode.conf.
